### PR TITLE
Fix plotly eventdata undefined val

### LINKED ISSUE #4354: Click and Hover data not working for Plotly pie chart: not serializable
I'm on the current `main` branch of Panel and using plotly 5.13.0. I'm working on #4350 and experience that I cannot get `click_data` or `hover_data` working for a Plotly Pie plot. When I look in the browser console after hovering or clicking the plot I see the error

```bash
Uncaught Error: [object Undefined] is not serializable
```

image

```python
import pandas as pd
import param as pm
import panel as pn
import plotly.express as px

df = pd.DataFrame({"ticker": ["A", "B", "C"], "value": [1, 2, 3]})


def portfolio_distribution(_=None, data=df):
    """Returns the distribution of the portfolio"""
    portfolio_total = data["value"].sum()

    fig = px.pie(
        data,
        values="value",
        names="ticker",
        hole=0.3,
        title=f"Portfolio Total ${portfolio_total:,.0f}",       
    )
    fig.layout.autosize = True
    return fig


plot = pn.pane.Plotly(
    portfolio_distribution(),
    config={"responsive": True},
    sizing_mode="stretch_both",
)

pn.Column(
    plot.param.hover_data,
    plot.param.click_data,
    plot,
    height=800,
    sizing_mode="stretch_width",
).servable()
```

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Fixes #4354 

## Root Cause

After logging values in the assignments below I could see that for example `this.model.click_data` was assigned a value that contained the key `text` with a value of `undefined`. This caused the error `Uncaught Error: [object Undefined] is not serializable`.

image

## Solution

The solution is to adding further clean up to `filterEventData`.

## The solution works

https://user-images.githubusercontent.com/42288570/215309387-55b8131c-2c39-4186-b3d8-5dac13b2433e.mp4

```python
import pandas as pd
import param as pm
import panel as pn
import plotly.express as px

df = pd.DataFrame({"ticker": ["A", "B", "C"], "value": [1, 2, 3]})


def portfolio_distribution(_=None, data=df):
    """Returns the distribution of the portfolio"""
    portfolio_total = data["value"].sum()

    fig = px.pie(
        data,
        values="value",
        names="ticker",
        hole=0.3,
        title=f"Portfolio Total ${portfolio_total:,.0f}",       
    )
    fig.layout.autosize = True
    return fig


plot = pn.pane.Plotly(
    portfolio_distribution(),
    config={"responsive": True},
    sizing_mode="stretch_both",
)

pn.Column(
    plot.param.hover_data,
    plot.param.click_data,
    plot,
    height=800,
    sizing_mode="stretch_width",
).servable()
```

### CODE REVIEW

File: panel/models/plotly.ts [hunk 1]
```diff
@@ -54,8 +54,8 @@ const filterEventData = (gd: any, eventData: any, event: string) => {
             for (let property in fullPoint) {
               const val = fullPoint[property];
               if (fullPoint.hasOwnProperty(property) &&
-                  !Array.isArray(val) && !isPlainObject(val))  {
-
+                  !Array.isArray(val) && !isPlainObject(val) &&
+                  val!==undefined)  {
```
Comment (philippjfr) [inline panel/models/plotly.ts:58]:
```suggestion
                  !Array.isArray(val) && !isPlainObject(val) &&
                  val !== undefined)  {
```
